# Pandas Day 1

In [6]:
import pandas as pd

In [2]:
df = pd.read_csv("emp.csv")

NameError: name 'pd' is not defined

In [5]:
type(df)

pandas.core.frame.DataFrame

In [10]:
ser = df['eno']

In [11]:
type(ser)

pandas.core.series.Series

In [16]:
# SQL : select eno,salary from emp

df1 = df[['eno','salary']]

# or 

list_col = ['eno','salary']

df2 = df[list_col]

In [13]:
type(df1)

pandas.core.frame.DataFrame

In [21]:
df2.head(1)

   eno  salary
0   10    1000

In [23]:
df2.tail()

    eno  salary
42   43    2100
43   44    1900
44   45    1800
45   46    1700
46   47    1600

In [26]:
df = pd.read_csv("emp.csv",header=0)

In [28]:
df = pd.read_csv("emp.csv",header=1)

In [30]:
df = pd.read_csv("emp.csv",header=None)

In [70]:
df = pd.read_csv("emp.csv",usecols=['eno','deptno','doj'])

In [38]:
df.head()

   eno  deptno         doj
0   10      10  2018-05-14
1    2      10  2017-03-22
2    8      20  2020-11-30
3    4      10  2019-08-18
4    5      10  2021-02-10

In [46]:
df.iloc[[2,4]]

   eno  deptno         doj
2    8      20  2020-11-30
4    5      10  2021-02-10

In [47]:
type(df.iloc[[2,4]])

pandas.core.frame.DataFrame

In [69]:
df = pd.read_csv("emp.csv",index_col='eno')

In [61]:
df.head()

      ename  salary  deptno         doj
eno
10    Amber    1000      10  2018-05-14
2      Amar    1000      10  2017-03-22
8     Sagar    1000      20  2020-11-30
4    Thomas    1000      10  2019-08-18
5      Jade    2000      10  2021-02-10

In [59]:
# SQL : select * from emp where eno=20
df.loc[[20]]

    ename  salary  deptno         doj
eno
20   John    2300      30  2018-10-29

In [60]:
# SQL : select * from emp where eno= in (20,25,30)
df.loc[[20,25,30]]

      ename  salary  deptno         doj
eno
20     John    2300      30  2018-10-29
25    Meena    2000      20  2020-03-13
30   Suresh    1100      10  2018-09-09

In [72]:
df = pd.read_csv("emp.csv")

In [73]:
df.dtypes

eno        int64
ename     object
salary    object
deptno     int64
doj       object
dtype: object

In [76]:
df = pd.read_csv("emp.csv",dtype={'eno':float})

In [77]:
df.dtypes

eno       float64
ename      object
salary     object
deptno      int64
doj        object
dtype: object

In [78]:
df

     eno    ename    salary  deptno         doj
0   10.0    Amber      1000      10  2018-05-14
1    2.0     Amar      1000      10  2017-03-22
2    8.0    Sagar      1000      20  2020-11-30
3    4.0   Thomas      1000      10  2019-08-18
4    5.0     Jade   2000.34      10  2021-02-10
5    6.0    Smith  thousand      10  2016-12-01
6    7.0   Robert      3000      20  2023-06-25
7    3.0     Nick      1000      30  2015-09-15
8    9.0    Naman      4000      30  2020-01-20
9    1.0    Vikas      1000      30  2017-10-03
10  11.0   Dennis     41000      30  2024-01-05
11  12.0    Karan      2200      20  2018-06-16
12  13.0   Simran      1500      10  2019-12-19
13  14.0     Amit      2000      30  2022-04-09
14  15.0     Neha      1700      20  2021-07-22
15  16.0    Rahul      1200      10  2016-03-28
16  17.0    Divya      3000      30  2015-11-11
17  18.0   Rakesh      1800      10  2020-09-04
18  19.0   Monica      2500      20  2023-08-07
19  20.0     John      2300      30  2018-10-29
20  21.0    Sneha      2700      10  2022-12-14
21  22.0    David      1000      20  2017-02-17
22  23.0    Anita      1500      30  2019-05-21
23  24.0    Vinod      1800      10  2016-07-30
24  25.0    Meena      2000      20  2020-03-13
25  26.0    Harsh      1600      10  2021-09-25
26  27.0   Kavita      1400      30  2019-01-06
27  28.0    Mohan      1300      10  2015-04-17
28  29.0    Priya      1200      20  2023-02-11
29  30.0   Suresh      1100      10  2018-09-09
30  31.0     Rani      1900      20  2022-11-03
31  32.0     Ajay      2100      10  2020-06-26
32  33.0    Nidhi      2400      30  2016-05-12
33  34.0    Vivek      2000      20  2017-07-31
34  35.0    Seema      3000      10  2021-10-15
35  36.0     Ritu      3200      20  2023-05-01
36  37.0    Kunal      2800      30  2015-08-22
37  38.0     Alok      2700      10  2019-03-02
38  39.0   Poonam      2600      20  2022-02-05
39  40.0     Yash      2500      30  2020-07-19
40  41.0     Nina      2300      20  2018-12-28
41  42.0    Tarun      2200      10  2021-01-09
42  43.0    Geeta      2100      30  2017-11-14
43  44.0    Ashok      1900      10  2016-06-08
44  45.0  Sanjana      1800      20  2023-03-17
45  46.0    Manoj      1700      30  2019-07-24
46  47.0    Payal      1600      20  2015-10-10

In [79]:
df

     eno    ename    salary  deptno         doj
0   10.0    Amber      1000      10  2018-05-14
1    2.0     Amar      1000      10  2017-03-22
2    8.0    Sagar      1000      20  2020-11-30
3    4.0   Thomas      1000      10  2019-08-18
4    5.0     Jade   2000.34      10  2021-02-10
5    6.0    Smith  thousand      10  2016-12-01
6    7.0   Robert      3000      20  2023-06-25
7    3.0     Nick      1000      30  2015-09-15
8    9.0    Naman      4000      30  2020-01-20
9    1.0    Vikas      1000      30  2017-10-03
10  11.0   Dennis     41000      30  2024-01-05
11  12.0    Karan      2200      20  2018-06-16
12  13.0   Simran      1500      10  2019-12-19
13  14.0     Amit      2000      30  2022-04-09
14  15.0     Neha      1700      20  2021-07-22
15  16.0    Rahul      1200      10  2016-03-28
16  17.0    Divya      3000      30  2015-11-11
17  18.0   Rakesh      1800      10  2020-09-04
18  19.0   Monica      2500      20  2023-08-07
19  20.0     John      2300      30  2018-10-29
20  21.0    Sneha      2700      10  2022-12-14
21  22.0    David      1000      20  2017-02-17
22  23.0    Anita      1500      30  2019-05-21
23  24.0    Vinod      1800      10  2016-07-30
24  25.0    Meena      2000      20  2020-03-13
25  26.0    Harsh      1600      10  2021-09-25
26  27.0   Kavita      1400      30  2019-01-06
27  28.0    Mohan      1300      10  2015-04-17
28  29.0    Priya      1200      20  2023-02-11
29  30.0   Suresh      1100      10  2018-09-09
30  31.0     Rani      1900      20  2022-11-03
31  32.0     Ajay      2100      10  2020-06-26
32  33.0    Nidhi      2400      30  2016-05-12
33  34.0    Vivek      2000      20  2017-07-31
34  35.0    Seema      3000      10  2021-10-15
35  36.0     Ritu      3200      20  2023-05-01
36  37.0    Kunal      2800      30  2015-08-22
37  38.0     Alok      2700      10  2019-03-02
38  39.0   Poonam      2600      20  2022-02-05
39  40.0     Yash      2500      30  2020-07-19
40  41.0     Nina      2300      20  2018-12-28
41  42.0    Tarun      2200      10  2021-01-09
42  43.0    Geeta      2100      30  2017-11-14
43  44.0    Ashok      1900      10  2016-06-08
44  45.0  Sanjana      1800      20  2023-03-17
45  46.0    Manoj      1700      30  2019-07-24
46  47.0    Payal      1600      20  2015-10-10

In [97]:
# Read from line 11 ( index : 10) to 20 ( index : 19)
df1 = pd.read_csv("emp.csv")
df1.iloc[9:19]

    eno   ename salary  deptno         doj
9     1   Vikas   1000      30  2017-10-03
10   11  Dennis  41000      30  2024-01-05
11   12   Karan   2200      20  2018-06-16
12   13  Simran   1500      10  2019-12-19
13   14    Amit   2000      30  2022-04-09
14   15    Neha   1700      20  2021-07-22
15   16   Rahul   1200      10  2016-03-28
16   17   Divya   3000      30  2015-11-11
17   18  Rakesh   1800      10  2020-09-04
18   19  Monica   2500      20  2023-08-07

In [94]:
# Read only 10 to 20 lines from the file
df2 = pd.read_csv("emp.csv",skiprows=10,nrows=10,header=None)

In [95]:
df2

    0       1      2   3           4
0   1   Vikas   1000  30  2017-10-03
1  11  Dennis  41000  30  2024-01-05
2  12   Karan   2200  20  2018-06-16
3  13  Simran   1500  10  2019-12-19
4  14    Amit   2000  30  2022-04-09
5  15    Neha   1700  20  2021-07-22
6  16   Rahul   1200  10  2016-03-28
7  17   Divya   3000  30  2015-11-11
8  18  Rakesh   1800  10  2020-09-04
9  19  Monica   2500  20  2023-08-07

In [98]:
df

    0       1      2   3           4
0   1   Vikas   1000  30  2017-10-03
1  11  Dennis  41000  30  2024-01-05
2  12   Karan   2200  20  2018-06-16
3  13  Simran   1500  10  2019-12-19
4  14    Amit   2000  30  2022-04-09
5  15    Neha   1700  20  2021-07-22
6  16   Rahul   1200  10  2016-03-28
7  17   Divya   3000  30  2015-11-11
8  18  Rakesh   1800  10  2020-09-04
9  19  Monica   2500  20  2023-08-07

In [102]:
df = pd.read_csv("emp.csv",parse_dates=['doj'])

In [103]:
df.dtypes

eno                int64
ename             object
salary            object
deptno             int64
doj       datetime64[ns]
dtype: object

In [108]:
df['doj'].dt.month.head()

0     5
1     3
2    11
3     8
4     2
Name: doj, dtype: int32

In [110]:
df['doj'].dt.year.head()

0    2018
1    2017
2    2020
3    2019
4    2021
Name: doj, dtype: int32

In [111]:
df['doj'].dt.day.head()

0    14
1    22
2    30
3    18
4    10
Name: doj, dtype: int32

# Performance Optimization

In [130]:
# Read the entire data form the file in one go itself ( lower perfromavce but correct data types inferred)
df = pd.read_csv("emp.csv",low_memory=False)  

# Read the data in chunks form the file ( Higher perfromance)
df = pd.read_csv("emp.csv",low_memory=True)

In [116]:
for chnk in pd.read_csv("emp.csv",chunksize=5):
    print(chnk)

   eno   ename   salary  deptno         doj
0   10   Amber  1000.00      10  2018-05-14
1    2    Amar  1000.00      10  2017-03-22
2    8   Sagar  1000.00      20  2020-11-30
3    4  Thomas  1000.00      10  2019-08-18
4    5    Jade  2000.34      10  2021-02-10
   eno   ename    salary  deptno         doj
5    6   Smith  thousand      10  2016-12-01
6    7  Robert      3000      20  2023-06-25
7    3    Nick      1000      30  2015-09-15
8    9   Naman      4000      30  2020-01-20
9    1   Vikas      1000      30  2017-10-03
    eno   ename  salary  deptno         doj
10   11  Dennis   41000      30  2024-01-05
11   12   Karan    2200      20  2018-06-16
12   13  Simran    1500      10  2019-12-19
13   14    Amit    2000      30  2022-04-09
14   15    Neha    1700      20  2021-07-22
    eno   ename  salary  deptno         doj
15   16   Rahul    1200      10  2016-03-28
16   17   Divya    3000      30  2015-11-11
17   18  Rakesh    1800      10  2020-09-04
18   19  Monica    2500      20  2023-08-07
19   20    John    2300      30  2018-10-29
    eno  ename  salary  deptno         doj
20   21  Sneha    2700      10  2022-12-14
21   22  David    1000      20  2017-02-17
22   23  Anita    1500      30  2019-05-21
23   24  Vinod    1800      10  2016-07-30
24   25  Meena    2000      20  2020-03-13
    eno   ename  salary  deptno         doj
25   26   Harsh    1600      10  2021-09-25
26   27  Kavita    1400      30  2019-01-06
27   28   Mohan    1300      10  2015-04-17
28   29   Priya    1200      20  2023-02-11
29   30  Suresh    1100      10  2018-09-09
    eno  ename  salary  deptno         doj
30   31   Rani    1900      20  2022-11-03
31   32   Ajay    2100      10  2020-06-26
32   33  Nidhi    2400      30  2016-05-12
33   34  Vivek    2000      20  2017-07-31
34   35  Seema    3000      10  2021-10-15
    eno   ename  salary  deptno         doj
35   36    Ritu    3200      20  2023-05-01
36   37   Kunal    2800      30  2015-08-22
37   38    Alok    2700      10  2019-03-02
38   39  Poonam    2600      20  2022-02-05
39   40    Yash    2500      30  2020-07-19
    eno    ename  salary  deptno         doj
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
    eno  ename  salary  deptno         doj
45   46  Manoj    1700      30  2019-07-24
46   47  Payal    1600      20  2015-10-10

In [121]:
# encoding

df = pd.read_csv("emp.csv",encoding='cp1251')

In [126]:
df1 = pd.read_csv("file.csv",encoding='cp1251')
df1

           name
0  а¤­а¤ѕа¤°а¤¤

In [127]:
df2 = pd.read_csv("file.csv",encoding='utf-8')
df2

   name
0  भारत

In [128]:
df3 = pd.read_csv("file.csv",encoding='latin1')
df3

           name
0  à¤­à¤¾à¤°à¤¤

In [3]:
df.to_csv("output.csv",index=False)

NameError: name 'df' is not defined

In [ ]:
df = pd.read_csv("emp.csv")

# Filter ( where clause in SQL)

In [156]:
# get the data only for deptno=10
# SQL: select * from emp where deptno=10

df[df['deptno'] == 10]

# or 
deptno_10 = df['deptno'] == 10
df[deptno_10]

    eno   ename    salary  deptno         doj
0    10   Amber      1000      10  2018-05-14
1     2    Amar      1000      10  2017-03-22
3     4  Thomas      1000      10  2019-08-18
4     5    Jade   2000.34      10  2021-02-10
5     6   Smith  thousand      10  2016-12-01
12   13  Simran      1500      10  2019-12-19
15   16   Rahul      1200      10  2016-03-28
17   18  Rakesh      1800      10  2020-09-04
20   21   Sneha      2700      10  2022-12-14
23   24   Vinod      1800      10  2016-07-30
25   26   Harsh      1600      10  2021-09-25
27   28   Mohan      1300      10  2015-04-17
29   30  Suresh      1100      10  2018-09-09
31   32    Ajay      2100      10  2020-06-26
34   35   Seema      3000      10  2021-10-15
37   38    Alok      2700      10  2019-03-02
41   42   Tarun      2200      10  2021-01-09
43   44   Ashok      1900      10  2016-06-08

In [164]:
# get the data only for deptno=10 and salary > 2K
# SQL: select * from emp where deptno=10

fil1 = df['deptno']==10
fil2 = df['salary']>2000
df_ans = df[fil1 & fil2]
df_ans

    eno  ename  salary  deptno         doj
20   21  Sneha    2700      10  2022-12-14
31   32   Ajay    2100      10  2020-06-26
34   35  Seema    3000      10  2021-10-15
37   38   Alok    2700      10  2019-03-02
41   42  Tarun    2200      10  2021-01-09

In [165]:
# get the data only for deptno=10 or salary > 2K
# SQL: select * from emp where deptno=10

fil1 = df['deptno']==10
fil2 = df['salary']>2000
df_ans = df[fil1 | fil2]
df_ans

    eno   ename  salary  deptno         doj
0    10   Amber    1000      10  2018-05-14
1     2    Amar    1000      10  2017-03-22
3     4  Thomas    1000      10  2019-08-18
4     5    Jade    2000      10  2021-02-10
5     6   Smith    1000      10  2016-12-01
6     7  Robert    3000      20  2023-06-25
8     9   Naman    4000      30  2020-01-20
10   11  Dennis   41000      30  2024-01-05
11   12   Karan    2200      20  2018-06-16
12   13  Simran    1500      10  2019-12-19
15   16   Rahul    1200      10  2016-03-28
16   17   Divya    3000      30  2015-11-11
17   18  Rakesh    1800      10  2020-09-04
18   19  Monica    2500      20  2023-08-07
19   20    John    2300      30  2018-10-29
20   21   Sneha    2700      10  2022-12-14
23   24   Vinod    1800      10  2016-07-30
25   26   Harsh    1600      10  2021-09-25
27   28   Mohan    1300      10  2015-04-17
29   30  Suresh    1100      10  2018-09-09
31   32    Ajay    2100      10  2020-06-26
32   33   Nidhi    2400      30  2016-05-12
34   35   Seema    3000      10  2021-10-15
35   36    Ritu    3200      20  2023-05-01
36   37   Kunal    2800      30  2015-08-22
37   38    Alok    2700      10  2019-03-02
38   39  Poonam    2600      20  2022-02-05
39   40    Yash    2500      30  2020-07-19
40   41    Nina    2300      20  2018-12-28
41   42   Tarun    2200      10  2021-01-09
42   43   Geeta    2100      30  2017-11-14
43   44   Ashok    1900      10  2016-06-08

In [166]:
# get the data only for (deptno=10 and salary > 2K)  or deptno=30
# SQL: select * from emp where (deptno=10 and salary > 2000) or  deptno=30

fil1 = df['deptno']==10
fil2 = df['salary']>2000
fil3 = df['deptno']==30
df_ans = df[(fil1 & fil2)|fil3]
df_ans

    eno   ename  salary  deptno         doj
7     3    Nick    1000      30  2015-09-15
8     9   Naman    4000      30  2020-01-20
9     1   Vikas    1000      30  2017-10-03
10   11  Dennis   41000      30  2024-01-05
13   14    Amit    2000      30  2022-04-09
16   17   Divya    3000      30  2015-11-11
19   20    John    2300      30  2018-10-29
20   21   Sneha    2700      10  2022-12-14
22   23   Anita    1500      30  2019-05-21
26   27  Kavita    1400      30  2019-01-06
31   32    Ajay    2100      10  2020-06-26
32   33   Nidhi    2400      30  2016-05-12
34   35   Seema    3000      10  2021-10-15
36   37   Kunal    2800      30  2015-08-22
37   38    Alok    2700      10  2019-03-02
39   40    Yash    2500      30  2020-07-19
41   42   Tarun    2200      10  2021-01-09
42   43   Geeta    2100      30  2017-11-14
45   46   Manoj    1700      30  2019-07-24

# Sorting ( SQL equivalent is order by)

In [171]:
# SQL : select * from emp order by depnto asc

# Sort the data in deptno ascending order
df.sort_values(by='deptno')
# or 
df.sort_values(by='deptno', ascending=True)

# Sort the data in deptno descending order
df.sort_values(by='deptno',ascending=False).head()

    eno   ename  salary  deptno         doj
16   17   Divya    3000      30  2015-11-11
10   11  Dennis   41000      30  2024-01-05
36   37   Kunal    2800      30  2015-08-22
26   27  Kavita    1400      30  2019-01-06
22   23   Anita    1500      30  2019-05-21

In [177]:
# SQL : select * from emp order by deptno asc,salary desc

df.sort_values(by=['deptno','salary'],ascending=[True,False]).head()

    eno  ename  salary  deptno         doj
34   35  Seema    3000      10  2021-10-15
20   21  Sneha    2700      10  2022-12-14
37   38   Alok    2700      10  2019-03-02
41   42  Tarun    2200      10  2021-01-09
31   32   Ajay    2100      10  2020-06-26

In [178]:
df.sort_index(ascending=False).head()

    eno    ename  salary  deptno         doj
46   47    Payal    1600      20  2015-10-10
45   46    Manoj    1700      30  2019-07-24
44   45  Sanjana    1800      20  2023-03-17
43   44    Ashok    1900      10  2016-06-08
42   43    Geeta    2100      30  2017-11-14

In [8]:
emp_dict = {"eno":[1,2,3],"ename":['A','B','C']}

In [180]:
emp_dict

{'eno': [1, 2, 3], 'ename': ['A', 'B', 'C']}

In [182]:
type(emp_dict)

dict

In [11]:
df1 = pd.DataFrame(emp_dict,index=[100,21,34])
df1

     eno ename
100    1     A
21     2     B
34     3     C

In [190]:
df1.sort_index()

     eno ename
21     2     B
34     3     C
100    1     A

In [198]:
df_sort_ans = df.sort_values(by=['deptno','salary'],ascending=[True,False])
df_sort_ans
df.sort_values(by=['deptno','salary'],ascending=[True,False],inplace=True)

In [200]:
df =

    eno    ename  salary  deptno         doj
34   35    Seema    3000      10  2021-10-15
20   21    Sneha    2700      10  2022-12-14
37   38     Alok    2700      10  2019-03-02
41   42    Tarun    2200      10  2021-01-09
31   32     Ajay    2100      10  2020-06-26
4     5     Jade    2000      10  2021-02-10
43   44    Ashok    1900      10  2016-06-08
17   18   Rakesh    1800      10  2020-09-04
23   24    Vinod    1800      10  2016-07-30
25   26    Harsh    1600      10  2021-09-25
12   13   Simran    1500      10  2019-12-19
27   28    Mohan    1300      10  2015-04-17
15   16    Rahul    1200      10  2016-03-28
29   30   Suresh    1100      10  2018-09-09
0    10    Amber    1000      10  2018-05-14
1     2     Amar    1000      10  2017-03-22
3     4   Thomas    1000      10  2019-08-18
5     6    Smith    1000      10  2016-12-01
35   36     Ritu    3200      20  2023-05-01
6     7   Robert    3000      20  2023-06-25
38   39   Poonam    2600      20  2022-02-05
18   19   Monica    2500      20  2023-08-07
40   41     Nina    2300      20  2018-12-28
11   12    Karan    2200      20  2018-06-16
24   25    Meena    2000      20  2020-03-13
33   34    Vivek    2000      20  2017-07-31
30   31     Rani    1900      20  2022-11-03
44   45  Sanjana    1800      20  2023-03-17
14   15     Neha    1700      20  2021-07-22
46   47    Payal    1600      20  2015-10-10
28   29    Priya    1200      20  2023-02-11
2     8    Sagar    1000      20  2020-11-30
21   22    David    1000      20  2017-02-17
10   11   Dennis   41000      30  2024-01-05
8     9    Naman    4000      30  2020-01-20
16   17    Divya    3000      30  2015-11-11
36   37    Kunal    2800      30  2015-08-22
39   40     Yash    2500      30  2020-07-19
32   33    Nidhi    2400      30  2016-05-12
19   20     John    2300      30  2018-10-29
42   43    Geeta    2100      30  2017-11-14
13   14     Amit    2000      30  2022-04-09
45   46    Manoj    1700      30  2019-07-24
22   23    Anita    1500      30  2019-05-21
26   27   Kavita    1400      30  2019-01-06
7     3     Nick    1000      30  2015-09-15
9     1    Vikas    1000      30  2017-10-03

In [208]:
df = pd.read_csv("emp.csv")
df

    eno    ename  salary  deptno         doj
0    10    Amber    1000      10  2018-05-14
1     2     Amar    1000      10  2017-03-22
2     8    Sagar    1000      20  2020-11-30
3     4   Thomas    1000      10  2019-08-18
4     5     Jade    2000      10  2021-02-10
5     6    Smith    1000      10  2016-12-01
6     7   Robert    3000      20  2023-06-25
7     3     Nick    1000      30  2015-09-15
8     9    Naman    4000      30  2020-01-20
9     1    Vikas    1000      30  2017-10-03
10   11   Dennis   41000      30  2024-01-05
11   12    Karan    2200      20  2018-06-16
12   13   Simran    1500      10  2019-12-19
13   14     Amit    2000      30  2022-04-09
14   15     Neha    1700      20  2021-07-22
15   16    Rahul    1200      10  2016-03-28
16   17    Divya    3000      30  2015-11-11
17   18   Rakesh    1800      10  2020-09-04
18   19   Monica    2500      20  2023-08-07
19   20     John    2300      30  2018-10-29
20   21    Sneha    2700      10  2022-12-14
21   22    David    1000      20  2017-02-17
22   23    Anita    1500      30  2019-05-21
23   24    Vinod    1800      10  2016-07-30
24   25    Meena    2000      20  2020-03-13
25   26    Harsh    1600      10  2021-09-25
26   27   Kavita    1400      30  2019-01-06
27   28    Mohan    1300      10  2015-04-17
28   29    Priya    1200      20  2023-02-11
29   30   Suresh    1100      10  2018-09-09
30   31     Rani    1900      20  2022-11-03
31   32     Ajay    2100      10  2020-06-26
32   33    Nidhi    2400      30  2016-05-12
33   34    Vivek    2000      20  2017-07-31
34   35    Seema    3000      10  2021-10-15
35   36     Ritu    3200      20  2023-05-01
36   37    Kunal    2800      30  2015-08-22
37   38     Alok    2700      10  2019-03-02
38   39   Poonam    2600      20  2022-02-05
39   40     Yash    2500      30  2020-07-19
40   41     Nina    2300      20  2018-12-28
41   42    Tarun    2200      10  2021-01-09
42   43    Geeta    2100      30  2017-11-14
43   44    Ashok    1900      10  2016-06-08
44   45  Sanjana    1800      20  2023-03-17
45   46    Manoj    1700      30  2019-07-24
46   47    Payal    1600      20  2015-10-10

In [213]:
ans_df = df.sort_values(by='deptno',inplace=True)
ans_df.head()

AttributeError: 'NoneType' object has no attribute 'head'

In [214]:
df.head(20)

    eno    ename  salary  deptno         doj
0    10    Amber    1000      10  2018-05-14
43   44    Ashok    1900      10  2016-06-08
41   42    Tarun    2200      10  2021-01-09
37   38     Alok    2700      10  2019-03-02
34   35    Seema    3000      10  2021-10-15
31   32     Ajay    2100      10  2020-06-26
29   30   Suresh    1100      10  2018-09-09
27   28    Mohan    1300      10  2015-04-17
25   26    Harsh    1600      10  2021-09-25
20   21    Sneha    2700      10  2022-12-14
17   18   Rakesh    1800      10  2020-09-04
15   16    Rahul    1200      10  2016-03-28
23   24    Vinod    1800      10  2016-07-30
1     2     Amar    1000      10  2017-03-22
3     4   Thomas    1000      10  2019-08-18
4     5     Jade    2000      10  2021-02-10
5     6    Smith    1000      10  2016-12-01
12   13   Simran    1500      10  2019-12-19
6     7   Robert    3000      20  2023-06-25
44   45  Sanjana    1800      20  2023-03-17

# Grouping data ( similar to sql group by)

In [220]:
# get me emp count in every depratment
# select deptno,count(*) form emp group by deptno
var1 = df.groupby("deptno")["eno"].count()
var1

deptno
10    18
20    15
30    14
Name: eno, dtype: int64

In [218]:
type(var1)

pandas.core.series.Series

In [221]:
var2 = var1.reset_index()

In [222]:
type(var2)

pandas.core.frame.DataFrame

In [226]:
var2

   deptno  eno
0      10   18
1      20   15
2      30   14

In [229]:
var2.rename(columns = {'eno':"count_emp"})

   deptno  count_emp
0      10         18
1      20         15
2      30         14

In [242]:
# get me emp count in every depratment
# select deptno,count(*) form emp group by deptno,salary
var1 = df.groupby(["deptno","salary"])["eno"].count().reset_index()
var1.head()
var1.rename(columns = {'eno':"count_emp"}).head()

   deptno  salary  count_emp
0      10    1000          4
1      10    1100          1
2      10    1200          1
3      10    1300          1
4      10    1500          1

In [251]:
# get me emp count in every depratment
# select deptno,count(*) form emp group by deptno,salary
df.groupby('deptno').agg({"eno":"count","salary":"min"}).reset_index()

   deptno  eno  salary
0      10   18    1000
1      20   15    1000
2      30   14    1000

In [261]:
df = pd.read_csv("emp.csv")
df.dtypes

eno         int64
ename      object
salary    float64
deptno      int64
doj        object
dtype: object

In [268]:
fil1 = df['salary'] ==1000.455
df[fil1]

   eno  ename    salary  deptno         doj
0   10  Amber  1000.455      10  2018-05-14

In [294]:
df = pd.read_csv("emp.csv",parse_dates=["doj"])

In [287]:
df_ans = df["doj"].dt.year.reset_index()
type(df_ans)

pandas.core.frame.DataFrame

In [291]:
df_ans.groupby("doj")["doj"].count()

doj
2015    5
2016    5
2017    5
2018    5
2019    6
2020    6
2021    5
2022    4
2023    5
2024    1
Name: doj, dtype: int64

In [299]:
ans_df = df.sort_values(by='deptno',inplace=True)

In [307]:
ans_df

In [302]:
round(df['salary'],3) == 1000.455

0      True
12    False
5     False
4     False
3     False
2     False
1     False
15    False
17    False
23    False
25    False
27    False
29    False
31    False
34    False
37    False
41    False
43    False
20    False
46    False
18    False
21    False
11    False
24    False
14    False
28    False
35    False
33    False
38    False
40    False
44    False
6     False
30    False
8     False
45    False
32    False
22    False
9     False
36    False
10    False
39    False
16    False
42    False
26    False
7     False
19    False
13    False
Name: salary, dtype: bool

In [306]:
# To identify only values as decimal (NO Integer)
df[df['salary'] % 1 != 0]

    eno  ename    salary  deptno        doj
0    10  Amber  1000.455      10 2018-05-14
16   17  Divya  3000.340      30 2015-11-11